# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Tieude = QtWidgets.QLabel(parent=self.centralwidget)
        self.Tieude.setGeometry(QtCore.QRect(130, 40, 481, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Tieude.setFont(font)
        self.Tieude.setObjectName("Tieude")
        self.ogoiy = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ogoiy.setGeometry(QtCore.QRect(220, 120, 311, 41))
        self.ogoiy.setText("")
        self.ogoiy.setObjectName("ogoiy")
        self.nhapdapan = QtWidgets.QLabel(parent=self.centralwidget)
        self.nhapdapan.setGeometry(QtCore.QRect(110, 190, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.nhapdapan.setFont(font)
        self.nhapdapan.setObjectName("nhapdapan")
        self.ok = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ok.setGeometry(QtCore.QRect(450, 190, 81, 31))
        self.ok.setObjectName("ok")
        self.thoat = QtWidgets.QPushButton(parent=self.centralwidget)
        self.thoat.setGeometry(QtCore.QRect(240, 240, 81, 31))
        self.thoat.setObjectName("thoat")
        self.batdau = QtWidgets.QPushButton(parent=self.centralwidget)
        self.batdau.setGeometry(QtCore.QRect(280, 82, 101, 21))
        self.batdau.setObjectName("batdau")
        self.goiy = QtWidgets.QLabel(parent=self.centralwidget)
        self.goiy.setGeometry(QtCore.QRect(160, 140, 47, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.goiy.setFont(font)
        self.goiy.setObjectName("goiy")
        self.onhapdapan = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.onhapdapan.setGeometry(QtCore.QRect(220, 180, 221, 41))
        self.onhapdapan.setText("")
        self.onhapdapan.setObjectName("onhapdapan")
        self.choilai = QtWidgets.QPushButton(parent=self.centralwidget)
        self.choilai.setGeometry(QtCore.QRect(350, 240, 81, 31))
        self.choilai.setObjectName("choilai")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 80, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Tieude.setText(_translate("MainWindow", "Chào mừng bạn đến với game ĐOÁN TỪ của chúng tôi"))
        self.nhapdapan.setText(_translate("MainWindow", "Nhập đáp án:"))
        self.ok.setText(_translate("MainWindow", "Ok"))
        self.thoat.setText(_translate("MainWindow", "Thoát"))
        self.batdau.setText(_translate("MainWindow", "Bắt đâu"))
        self.goiy.setText(_translate("MainWindow", "Gợi ý:"))
        self.choilai.setText(_translate("MainWindow", "Chơi lại"))
        self.label.setText(_translate("MainWindow", "Điểm: 100"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
